---

- name: privileges > Setup Influx privileges
  command: >
    {{ manala_influxdb_influx_bin }}
    {% if item.database in manala_influxdb_admins %}
      -username '{{ manala_influxdb_admins[item.database].name }}'
      -password '{{ manala_influxdb_admins[item.database].password }}'
    {% endif %}
    -execute 'GRANT {{ item.grant }} ON "{{ item.database }}" TO "{{ item.user }}"'
  with_items: "{{ manala_influxdb_privileges }}"
  changed_when: false
