---

- name: users > Create Influx users
  command: >
    {{ manala_influxdb_influx_bin }}
    {% if item.database in manala_influxdb_admins %}
      -username '{{ manala_influxdb_admins[item.database].name }}'
      -password '{{ manala_influxdb_admins[item.database].password }}'
    {% endif %}
    -database '{{ item.database }}'
    -execute "CREATE USER {{ item.name }} WITH PASSWORD '{{ item.password }}'"
  with_items: "{{ manala_influxdb_users }}"
  changed_when: false
